
[font]
#normal = { family = "Iosevka Term", style = "regular"}
size = 15

[env]
TERM = 'xterm-256color'

[window]
padding = { x = 9, y = 4}

[general]
import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]
